#!/usr/bin/env bash
# Interactive bootstrap that populates .dev.vars with three env-scoped values.
#
# Does NOT touch ~/.env. Does NOT write ANTHROPIC_API_KEY anywhere - the
# worker never sees the org key. Org-level operations run via scripts/ops.ts,
# which reads the key from ~/.env at invocation.
#
# Run from managed-agents/cloudflare/:
#   ./scripts/bootstrap-dev-vars.sh
set -euo pipefail
cd "$(dirname "$0")/.."

DEV_VARS=".dev.vars"

if [[ -f "$DEV_VARS" ]]; then
  echo "$DEV_VARS already exists. Refusing to overwrite."
  echo "Delete it manually if you want to re-bootstrap, then re-run."
  exit 1
fi

echo "managed-agents/cloudflare — bootstrap .dev.vars"
echo
echo "This populates .dev.vars with three env-scoped values:"
echo "  ANTHROPIC_ENVIRONMENT_ID, ANTHROPIC_ENVIRONMENT_KEY, ANTHROPIC_WEBHOOK_SIGNING_KEY"
echo
echo "The org-scoped ANTHROPIC_API_KEY is NOT written here. Operations that"
echo "need it (env create, agent register, session create) run via scripts/ops.ts,"
echo "which reads it from ~/.env at invocation."
echo

echo "Step 1: pick or create a self-hosted environment."
echo "        Existing environments (via ops.ts, requires ANTHROPIC_API_KEY in ~/.env):"
if existing=$(bun scripts/ops.ts env list 2>/dev/null); then
  echo "$existing" | jq -r '.data[]? | "          \(.id)  \(.name)  type=\(.config.type)"' || true
else
  echo "          (could not list — ANTHROPIC_API_KEY missing or the endpoint isn't ready)"
fi
echo
read -r -p "Environment id (env_…): " ENV_ID
[[ -z "$ENV_ID" ]] && { echo "aborted"; exit 1; }

echo
echo "Step 2: in the Anthropic console, open the environment and click 'Generate environment key'."
echo "        URL: https://platform.claude.com/workspaces/default/environments/$ENV_ID"
read -r -s -p "Paste the environment key (sk-ant-oat01-…): " ENV_KEY
echo
[[ -z "$ENV_KEY" ]] && { echo "aborted"; exit 1; }

echo
echo "Step 3: in the Anthropic console under Webhooks, subscribe to session events for"
echo "        your worker URL and copy the signing key."
read -r -s -p "Paste the webhook signing key (whsec_…): " SIGNING_KEY
echo
[[ -z "$SIGNING_KEY" ]] && { echo "aborted"; exit 1; }

umask 077
cat > "$DEV_VARS" <<EOF
# Generated by scripts/bootstrap-dev-vars.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Env-scoped values only. ANTHROPIC_API_KEY never lives here.
ANTHROPIC_ENVIRONMENT_ID="$ENV_ID"
ANTHROPIC_ENVIRONMENT_KEY="$ENV_KEY"
ANTHROPIC_WEBHOOK_SIGNING_KEY="$SIGNING_KEY"
EOF

echo
echo "Wrote $DEV_VARS (mode 600). Ready for: bun run dev"
